// Mirrors the hand-made parts of the pipeline (scripts, docs, queue/registry JSON,
// HyperFrames compositions, the Main Channel Video editing skills) into a separate
// folder that is its own git repo, commits, and pushes if a private remote is set.
// Videos, audio, browser logins and every secret are left out.
//
//   node scripts/backup-private.js            mirror + commit (+ push if remote exists)
//   node scripts/backup-private.js --dry-run  list what would be copied
const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');

const DESKTOP = path.join(__dirname, '..', '..');
const DEST = path.join(DESKTOP, 'Youtube-pipeline-backup');
const MAX_BYTES = 3 * 1024 * 1024;

const SOURCES = [
  { from: path.join(DESKTOP, 'Youtube'), to: 'youtube' },
  { from: path.join(DESKTOP, 'Main Channel Video'), to: 'main-channel-video' },
];

const SKIP_DIRS = new Set([
  'node_modules', '.git', '.venv', 'venv', '__pycache__', 'instagram_browser_profile', 'snapshots',
  'archive', 'temp', 'uploads', 'scratch', 'logs', '.cache', 'debug_screenshots', 'frames', 'clip1_frames', 'clip2_frames',
]);
const KEEP_EXT = new Set(['.js', '.mjs', '.cjs', '.ts', '.py', '.bat', '.ps1', '.sh', '.md', '.json', '.html', '.css', '.yml', '.yaml', '.txt', '.conf', '.toml', '.cfg', '.ini']);
const SECRET_NAME = /(^\.env|token|credential|secret|cookie|\.pem$|\.key$)/i;
const SECRET_TEXT = /(EAA[A-Za-z0-9]{40,}|IGAA[A-Za-z0-9_-]{40,}|AIza[0-9A-Za-z_-]{35}|sk-[A-Za-z0-9_-]{30,}|ya29\.[A-Za-z0-9_-]{20,}|GOCSPX-[A-Za-z0-9_-]{10,}|"refresh_token"\s*:\s*"[^"]{10,})/;

function walk(dir, out = []) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (entry.isDirectory()) {
      if (!SKIP_DIRS.has(entry.name) && !entry.name.startsWith('snapshots')) walk(path.join(dir, entry.name), out);
      continue;
    }
    const file = path.join(dir, entry.name);
    const ext = path.extname(entry.name).toLowerCase();
    if (!KEEP_EXT.has(ext) || SECRET_NAME.test(entry.name) || entry.name === 'package-lock.json') continue;
    if (fs.statSync(file).size <= MAX_BYTES) out.push(file);
  }
  return out;
}

function git(args, opts = {}) {
  return execFileSync('git', args, { cwd: DEST, encoding: 'utf8', stdio: opts.inherit ? 'inherit' : ['ignore', 'pipe', 'pipe'] });
}

function main() {
  const dryRun = process.argv.includes('--dry-run');
  const plan = [];
  const blocked = [];
  for (const { from, to } of SOURCES) {
    if (!fs.existsSync(from)) continue;
    for (const file of walk(from)) {
      const text = fs.readFileSync(file, 'utf8');
      const target = path.join(DEST, to, path.relative(from, file));
      if (SECRET_TEXT.test(text)) blocked.push(path.relative(DESKTOP, file));
      else plan.push([file, target]);
    }
  }

  const totalKb = Math.round(plan.reduce((s, [f]) => s + fs.statSync(f).size, 0) / 1024);
  console.log(`📦 ${plan.length} files (${totalKb} KB) → ${DEST}`);
  if (blocked.length) {
    console.log(`🔒 Skipped ${blocked.length} file(s) that contain a token — move the token to .env:`);
    blocked.forEach((f) => console.log(`   ${f}`));
  }
  if (dryRun) {
    plan.slice(0, 40).forEach(([f]) => console.log(`   ${path.relative(DESKTOP, f)}`));
    if (plan.length > 40) console.log(`   ... and ${plan.length - 40} more`);
    return;
  }

  // Fresh mirror each time so deleted files disappear from the backup too.
  if (fs.existsSync(DEST)) {
    for (const entry of fs.readdirSync(DEST)) {
      if (entry !== '.git') fs.rmSync(path.join(DEST, entry), { recursive: true, force: true });
    }
  } else {
    fs.mkdirSync(DEST, { recursive: true });
  }
  for (const [from, to] of plan) {
    fs.mkdirSync(path.dirname(to), { recursive: true });
    fs.copyFileSync(from, to);
  }
  fs.writeFileSync(path.join(DEST, 'README.md'), `# Ratnakar pipeline backup (PRIVATE)\n\nAuto-generated by \`Youtube/scripts/backup-private.js\`. Do not edit here — edit the originals.\nLast run: ${new Date().toISOString()}\n`);

  if (!fs.existsSync(path.join(DEST, '.git'))) git(['init', '-b', 'main']);
  git(['add', '-A']);
  try {
    git(['diff', '--cached', '--quiet']);
    console.log('ℹ️ No changes since the last backup.');
  } catch {
    git(['commit', '-q', '-m', `backup ${new Date().toISOString().slice(0, 16).replace('T', ' ')}`]);
    console.log('✅ Backup committed.');
  }

  let remote = '';
  try {
    remote = git(['remote', 'get-url', 'origin']).trim();
  } catch {
    // no remote configured yet
  }
  if (!remote) {
    console.log('ℹ️ No private GitHub remote yet — backup is only on this laptop.');
    return;
  }
  git(['push', '-q', 'origin', 'main'], { inherit: true });
  console.log(`✅ Pushed to ${remote}`);
}

main();
